unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind-key r source-file ~/.tmux.conf \; display ".tmux.conf reloaded!"

bind-key T display-popup -w 90% -h 90%
bind-key g display-popup -w 90% -h 90% -d "#{pane_current_path}" -E "lazygit"
bind-key i display-popup -w 90% -h 90% -E "opencode"        # opencode

setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R


# bind-key i display-popup -E "viu image.png"   # image preview (if supported)

